dataloader_params:
  num_workers: AUTO
  pin_memory: true
  prefetch_factor: null
  use_fast_dataloader: false
dataset_params:
  csv_path: ./dataset_csvs/FFHQ_v1.csv
  horizontal_flip_p: 0.5
  vertical_flip_p: -1
define: true
dwt_params:
  affine_lr_multiplier: 0.1
  coeffs_scales_2d_version: AUTO
  init_affine_scales:
  - 2
  - 12
  - 12
  - 16
  scale_1d_coeffs: AUTO
  scale_2d_coeffs: false
  train_affine: true
  train_kernel: false
  use_affine: true
  wavelet: CDF-9/7
ema_params:
  decay: 0.9999
  exclude_buffers: false
  foreach: true
  kimg: 10
  min_decay: 0.0
  mode: base
  rampup: 0.05
  sema_kimg: null
  use_warmup: false
  warmup_gamma: 1.0
  warmup_power: 0.67
general_params:
  architecture: StyleWaveGAN
  img_shape_yxc:
  - 1024
  - 1024
  - 3
  load_from_checkpoint: true
  num_classes: 1
  num_fp16_res: 4
  start_resolution: 4
  target_resolution: 1024
  use_compilation: false
  use_diff_aug: true
  w_dim: 512
  z_dim: 192
  z_distribution: normal
logs_params:
  ckpts_freq_kimg: 10
  dir: ./results
  imgs_freq_kimg: 10
  imgs_grid_ncols: 6
  imgs_grid_nrows: 4
  logs_freq_kimg: 5
  max_ckpts: 5
  metrics_freq_kimg: 100
loss_params:
  D_reg_interval: 16
  G_reg_fade_kimg: 200
  G_reg_interval: 4
  blur_fade_kimg: 200
  blur_init_sigma: 10
  pl_batch_shrink: 2
  pl_decay: 0.01
  pl_no_weight_grad: true
  pl_weight: 2
  r1_gamma: 10
  style_mixing_prob: 0.75
  use_projection: false
metrics_params:
  metric1:
    batch_size: 32
    data_format: NHWC
    kimg: 50
    resize_in_model: true
    resize_method: area
    type: FID
  metric2:
    kimg: 50
    skip: true
    type: PPL
models_params:
  Discriminator:
    activation: lrelu
    architecture: skip
    channel_base: 16384
    channel_max: 512
    conv_clamp: 256
    conv_type: selfmod
    ffc_params:
      activation: lrelu
      conv_clamp: 256
      conv_norm: null
      conv_type: selfmod
      fft_norm: full
      lfu_mode: wavelet_full
      lfu_wavelet: CDF-9/7
      num_skipped_res: 1
      ratio_in_global: 0.25
      ratio_out_global: 0.25
      use_ffc: true
      use_lfu: true
    projection_params:
      head_architecture: swg-v2
      head_main_channels: null
      mixing_out_max_channels: null
      num_heads: 3
      use_projection: false
    resample_filter:
    - 1
    - 3
    - 3
    - 1
  Generator:
    Mapping:
      activation: silu
      lr_multiplier: 0.03
      num_layers: 3
      w_avg_beta: 0.998
    Synthesis:
      activation: silu
      architecture: skip
      channel_base: 16384
      channel_max: 512
      conv_clamp: 256
      fused_modconv_default: true
      init_torgb_wavelet_scales:
      - 1
      - 8
      - 8
      - 8
      input_impl_idx: 2
      input_type: Fourier
      resample_filter:
      - 1
      - 3
      - 3
      - 1
optimizers_params:
  Discriminator:
    betas:
    - 0.0
    - 0.99
    eps: 1e-8
    lr: 0.002
    type: adam
  Generator:
    betas:
    - 0.0
    - 0.99
    eps: 1e-8
    lr: 0.002
    type: adam
training_params:
  batch_size_per_gpu: 24
  bias_act_impl: cuda
  data_format: NCHW
  gpus:
  - 0
  - 1
  total_kimg: 25000
  upfirdn2d_impl: cuda
  use_custom_conv2d_op: true
